import StyleDictionary from 'style-dictionary';
import { existsSync, readFileSync, writeFileSync } from 'fs';

// Custom format: nested TypeScript constants
function tsTokensFormat({ dictionary }) {
  const tokens = {};
  dictionary.allTokens.forEach(token => {
    let obj = tokens;
    const path = token.path;
    for (let i = 0; i < path.length - 1; i++) {
      // Don't overwrite a leaf value with an object
      if (!obj[path[i]] || typeof obj[path[i]] !== 'object') {
        obj[path[i]] = {};
      }
      obj = obj[path[i]];
    }
    const key = path[path.length - 1];
    // Only set if not already an object with children
    if (typeof obj[key] !== 'object' || Object.keys(obj[key]).length === 0) {
      obj[key] = token.$value !== undefined ? token.$value : token.value;
    }
  });
  return [
    '// Auto-generated by Style Dictionary — DO NOT EDIT',
    '// Source: tokens/*.json',
    '',
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    '',
  ].join('\n');
}

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [{
        destination: 'variables.css',
        format: 'css/variables',
        options: { outputReferences: true }
      }]
    },
    scss: {
      transformGroup: 'scss',
      buildPath: 'build/scss/',
      files: [{
        destination: '_variables.scss',
        format: 'scss/variables',
        options: { outputReferences: true }
      }]
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'build/ts/',
      files: [{
        destination: 'tokens.ts',
        format: 'typescript/tokens',
      }]
    },
    json: {
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [{
        destination: 'tokens.json',
        format: 'json/flat',
      }]
    },
  },
  hooks: {
    formats: {
      'typescript/tokens': tsTokensFormat,
    }
  }
});

await sd.buildAllPlatforms();

// Generate token guide markdown
function generateTokenGuide() {
  // Read token files
  const colorTokens = JSON.parse(readFileSync('tokens/color.json', 'utf-8'));
  const typographyTokens = JSON.parse(readFileSync('tokens/typography.json', 'utf-8'));
  const spacingTokens = JSON.parse(readFileSync('tokens/spacing.json', 'utf-8'));
  const borderRadiusTokens = JSON.parse(readFileSync('tokens/borderRadius.json', 'utf-8'));
  const shadowTokens = JSON.parse(readFileSync('tokens/shadow.json', 'utf-8'));
  const animationTokens = JSON.parse(readFileSync('tokens/animation.json', 'utf-8'));

  let markdown = `# Compulocks Brand Token Guide
> Auto-generated from tokens/*.json — do not edit directly

`;

  // Colors section
  markdown += `## Colors

| Token | Value | Description |
|-------|-------|-------------|
`;

  function addColorTokens(obj, prefix = '') {
    Object.entries(obj).forEach(([key, val]) => {
      const path = prefix ? `${prefix}.${key}` : `color.${key}`;
      if (val && typeof val === 'object' && '$value' in val) {
        markdown += `| \`${path}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
      } else if (val && typeof val === 'object' && !('$value' in val)) {
        addColorTokens(val, path);
      }
    });
  }

  addColorTokens(colorTokens.color);

  // Typography section
  markdown += `
## Typography

### Font Families & Weights

| Token | Value | Description |
|-------|-------|-------------|
`;

  // Font families
  Object.entries(typographyTokens.font.family).forEach(([key, val]) => {
    markdown += `| \`font.family.${key}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
  });

  // Font weights
  Object.entries(typographyTokens.font.weight).forEach(([key, val]) => {
    markdown += `| \`font.weight.${key}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
  });

  // Text Styles
  markdown += `
### Text Styles

| Style | Font | Weight | Transform | Description |
|-------|------|--------|-----------|-------------|
`;

  Object.entries(typographyTokens.textStyle).forEach(([key, val]) => {
    const fontFamily = val.fontFamily?.$value || '';
    const fontWeight = val.fontWeight?.$value || '';
    const textTransform = val.textTransform?.$value || '';
    const description = val.$description || '';
    markdown += `| \`textStyle.${key}\` | ${fontFamily} | ${fontWeight} | ${textTransform} | ${description} |
`;
  });

  // Spacing section
  markdown += `
## Spacing Scale

| Token | Value | px | Description |
|-------|-------|-----|-------------|
`;

  Object.entries(spacingTokens.spacing).forEach(([key, val]) => {
    const remValue = val.$value;
    const pxValue = val.$description;
    markdown += `| \`spacing.${key}\` | \`${remValue}\` | ${pxValue} |
`;
  });

  // Border Radius section
  markdown += `
## Border Radius

| Token | Value | Description |
|-------|-------|-------------|
`;
  Object.entries(borderRadiusTokens.borderRadius).forEach(([key, val]) => {
    markdown += `| \`borderRadius.${key}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
  });

  // Shadow section
  markdown += `
## Shadows

| Token | Value | Description |
|-------|-------|-------------|
`;
  Object.entries(shadowTokens.shadow).forEach(([key, val]) => {
    markdown += `| \`shadow.${key}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
  });

  // Animation section
  markdown += `
## Animation Durations

| Token | Value | Description |
|-------|-------|-------------|
`;
  Object.entries(animationTokens.duration).forEach(([key, val]) => {
    markdown += `| \`duration.${key}\` | \`${val.$value}\` | ${val.$description || ''} |
`;
  });

  writeFileSync('token_guide.md', markdown, 'utf-8');
  console.log('Token guide generated → token_guide.md');
}

generateTokenGuide();

// Generate typography utility classes
// (writeFileSync is already imported at the top of the file)
const typographyUtilities = `/* Compulocks Typography Utility Classes */
/* Auto-generated from COMPULOCKS R&D AI Design Kit — do not edit */

.section-heading {
  font-family: 'Barlow Condensed', 'Arial Narrow', Arial, sans-serif;
  font-size: 69px;
  font-weight: 500;
  text-transform: capitalize;
  color: var(--color-brand-primary);
}

.slide-title {
  font-family: 'Barlow Condensed', 'Arial Narrow', Arial, sans-serif;
  font-size: 36px;
  font-weight: 500;
  text-transform: capitalize;
  color: var(--color-brand-primary);
}

.small-title {
  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif;
  font-size: 21px;
  font-weight: 600;
  color: var(--color-brand-primary);
}

.paragraph-text {
  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif;
  font-size: 18px;
  font-weight: 400;
  color: var(--color-brand-primary);
}

.small-text {
  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif;
  font-size: 12px;
  font-weight: 400;
  font-style: italic;
  color: var(--color-brand-primary);
}
`;

writeFileSync('build/css/typography.css', typographyUtilities, 'utf-8');
console.log('Typography utilities generated → build/css/typography.css');

const { execSync: exec } = await import('node:child_process');
try {
  if (existsSync('scripts/generate-living-html.mjs')) {
    exec('node scripts/generate-living-html.mjs', { cwd: process.cwd(), stdio: 'inherit' });
  } else {
    console.warn('[build] generate-living-html.mjs not found - skipping');
  }
} catch {
  console.warn('[build] generate-living-html.mjs failed - skipping');
}

try {
  exec('node scripts/sync-vault.mjs', { cwd: process.cwd(), stdio: 'inherit' });
} catch {
  console.warn('[build] sync-vault.mjs failed - vault not updated');
}
console.log('Build complete — outputs in build/');
