import StyleDictionary from 'style-dictionary';

// Custom format: nested TypeScript constants
function tsTokensFormat({ dictionary }) {
  const tokens = {};
  dictionary.allTokens.forEach(token => {
    let obj = tokens;
    const path = token.path;
    for (let i = 0; i < path.length - 1; i++) {
      // Don't overwrite a leaf value with an object
      if (!obj[path[i]] || typeof obj[path[i]] !== 'object') {
        obj[path[i]] = {};
      }
      obj = obj[path[i]];
    }
    const key = path[path.length - 1];
    // Only set if not already an object with children
    if (typeof obj[key] !== 'object' || Object.keys(obj[key]).length === 0) {
      obj[key] = token.$value !== undefined ? token.$value : token.value;
    }
  });
  return [
    '// Auto-generated by Style Dictionary — DO NOT EDIT',
    '// Source: tokens/*.json',
    '',
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    '',
  ].join('\n');
}

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [{
        destination: 'variables.css',
        format: 'css/variables',
        options: { outputReferences: true }
      }]
    },
    scss: {
      transformGroup: 'scss',
      buildPath: 'build/scss/',
      files: [{
        destination: '_variables.scss',
        format: 'scss/variables',
        options: { outputReferences: true }
      }]
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'build/ts/',
      files: [{
        destination: 'tokens.ts',
        format: 'typescript/tokens',
      }]
    },
    json: {
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [{
        destination: 'tokens.json',
        format: 'json/flat',
      }]
    },
  },
  hooks: {
    formats: {
      'typescript/tokens': tsTokensFormat,
    }
  }
});

await sd.buildAllPlatforms();
console.log('Build complete — outputs in build/');
